version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: new_password
      POSTGRES_DB: galeria
    ports:
      - "5433:5432"  # Mapeamos el puerto 5432 interno a 5433 externo para evitar conflictos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped  # 🔁 Auto-restart policy
volumes:
  postgres_data:
    driver: local

networks:
  my_network:
    name: my_network
    driver: bridge
